require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'ithnain' do
  use_unimodules!(exclude: ['expo-asset', 'expo-file-system', 'expo-image-loader', 'expo-permissions'])

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'ReactNativeAudioToolkit', :path => '../node_modules/@react-native-community/audio-toolkit'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'CometChatPro', '3.0.8'
  pod 'CometChatCalls', '2.1.1'

  target 'ithnainTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({'Flipper' => '0.95.0'})
  post_install do |installer|
    flipper_post_install(installer)
  end
end
